//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.24 at 11:30:02 AM CEST 
//


package de.drv.dsrv.spoc.extra.v1_3.jaxb.plugins;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EncryptionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EncryptionType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.extra-standard.de/namespace/plugins/1}AbstractTransformType">
 *       &lt;sequence>
 *         &lt;element name="Algorithm" type="{http://www.extra-standard.de/namespace/plugins/1}EncryptionAlgorithmType"/>
 *         &lt;element name="InputData" type="{http://www.extra-standard.de/namespace/plugins/1}DataType" minOccurs="0"/>
 *         &lt;element name="OutputData" type="{http://www.extra-standard.de/namespace/plugins/1}DataType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EncryptionType", propOrder = {
    "algorithm",
    "inputData",
    "outputData"
})
public class EncryptionType
    extends AbstractTransformType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "Algorithm", required = true)
    protected EncryptionAlgorithmType algorithm;
    @XmlElement(name = "InputData")
    protected DataType inputData;
    @XmlElement(name = "OutputData")
    protected DataType outputData;

    /**
     * Gets the value of the algorithm property.
     * 
     * @return
     *     possible object is
     *     {@link EncryptionAlgorithmType }
     *     
     */
    public EncryptionAlgorithmType getAlgorithm() {
        return algorithm;
    }

    /**
     * Sets the value of the algorithm property.
     * 
     * @param value
     *     allowed object is
     *     {@link EncryptionAlgorithmType }
     *     
     */
    public void setAlgorithm(EncryptionAlgorithmType value) {
        this.algorithm = value;
    }

    /**
     * Gets the value of the inputData property.
     * 
     * @return
     *     possible object is
     *     {@link DataType }
     *     
     */
    public DataType getInputData() {
        return inputData;
    }

    /**
     * Sets the value of the inputData property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataType }
     *     
     */
    public void setInputData(DataType value) {
        this.inputData = value;
    }

    /**
     * Gets the value of the outputData property.
     * 
     * @return
     *     possible object is
     *     {@link DataType }
     *     
     */
    public DataType getOutputData() {
        return outputData;
    }

    /**
     * Sets the value of the outputData property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataType }
     *     
     */
    public void setOutputData(DataType value) {
        this.outputData = value;
    }

}
