--------------------------------------------------------
-- Initiale Datenbankbefuellung Szenario Send Fetch
-- HSQLDB Database.
--------------------------------------------------------

INSERT INTO MANDATOR VALUES(2,'TEST')

INSERT INTO PROCEDURE_TYPE VALUES(2,'SCENARIO_SEND_FETCH')
INSERT INTO PROCEDURE_PHASE_CONFIGURATION VALUES(4,'PHASE3',NULL,2)
INSERT INTO PROCEDURE_PHASE_CONFIGURATION VALUES(5,'PHASE2',4,2)
INSERT INTO PROCEDURE_PHASE_CONFIGURATION VALUES(6,'PHASE1',NULL,2)
INSERT INTO PROCEDURE VALUES(2,'Datenabgleich','SEND_FETCH',2,2)