--------------------------------------------------------
-- Initiale Datenbankbefuellung Sterbedatenabgleich
-- HSQLDB Database.
--------------------------------------------------------

INSERT INTO MANDATOR VALUES(2,'DRV')

INSERT INTO PROCEDURE_TYPE VALUES(2,'STERBEMELDUNG_AUSLAND')
INSERT INTO PROCEDURE_PHASE_CONFIGURATION VALUES(4,'PHASE3',NULL,2)
INSERT INTO PROCEDURE_PHASE_CONFIGURATION VALUES(5,'PHASE2',4,2)
INSERT INTO PROCEDURE_PHASE_CONFIGURATION VALUES(6,'PHASE1',NULL,2)
INSERT INTO PROCEDURE VALUES(2,'SterbemeldungAusland','STMELD_AUSL',2,2)