
package de.extra.extraClientLight.webservice;

import javax.xml.ws.WebFault;

import de.drv.dsrv.spoc.extra.v1_3.jaxb.service.ExtraErrorType;


/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-10-16T08:59:46.199+02:00
 * Generated source version: 3.0.1
 */

@WebFault(name = "ExtraError", targetNamespace = "http://www.extra-standard.de/namespace/service/1")
public class ExtraFault extends Exception {
    
    private ExtraErrorType extraError;

    public ExtraFault() {
        super();
    }
    
    public ExtraFault(String message) {
        super(message);
    }
    
    public ExtraFault(String message, Throwable cause) {
        super(message, cause);
    }

    public ExtraFault(String message, ExtraErrorType extraError) {
        super(message);
        this.extraError = extraError;
    }

    public ExtraFault(String message, ExtraErrorType extraError, Throwable cause) {
        super(message, cause);
        this.extraError = extraError;
    }

    public ExtraErrorType getFaultInfo() {
        return this.extraError;
    }
}
