//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.24 at 11:30:02 AM CEST 
//


package de.drv.dsrv.spoc.extra.v1_3.jaxb.service;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ExtraErrorReasonType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ExtraErrorReasonType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyURI">
 *     &lt;enumeration value="http://www.extra-standard.de/reason/SERVICE_TEMPORARILY_UNAVAILABLE"/>
 *     &lt;enumeration value="http://www.extra-standard.de/reason/SERVICE_PERMANENTLY_UNAVAILABLE"/>
 *     &lt;enumeration value="http://www.extra-standard.de/reason/SERVICE_FAILURE"/>
 *     &lt;enumeration value="http://www.extra-standard.de/reason/INVALID_REQUEST"/>
 *     &lt;enumeration value="http://www.extra-standard.de/reason/UNSPECIFIED"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ExtraErrorReasonType")
@XmlEnum
public enum ExtraErrorReasonType {

    @XmlEnumValue("http://www.extra-standard.de/reason/SERVICE_TEMPORARILY_UNAVAILABLE")
    SERVICE_TEMPORARILY_UNAVAILABLE("http://www.extra-standard.de/reason/SERVICE_TEMPORARILY_UNAVAILABLE"),
    @XmlEnumValue("http://www.extra-standard.de/reason/SERVICE_PERMANENTLY_UNAVAILABLE")
    SERVICE_PERMANENTLY_UNAVAILABLE("http://www.extra-standard.de/reason/SERVICE_PERMANENTLY_UNAVAILABLE"),
    @XmlEnumValue("http://www.extra-standard.de/reason/SERVICE_FAILURE")
    SERVICE_FAILURE("http://www.extra-standard.de/reason/SERVICE_FAILURE"),
    @XmlEnumValue("http://www.extra-standard.de/reason/INVALID_REQUEST")
    INVALID_REQUEST("http://www.extra-standard.de/reason/INVALID_REQUEST"),
    @XmlEnumValue("http://www.extra-standard.de/reason/UNSPECIFIED")
    UNSPECIFIED("http://www.extra-standard.de/reason/UNSPECIFIED");
    private final String value;

    ExtraErrorReasonType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ExtraErrorReasonType fromValue(String v) {
        for (ExtraErrorReasonType c: ExtraErrorReasonType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
