//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.24 at 11:30:02 AM CEST 
//


package de.drv.dsrv.spoc.extra.v1_3.jaxb.service;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the de.drv.dsrv.spoc.extra.v1_3.jaxb.service package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ExtraError_QNAME = new QName("http://www.extra-standard.de/namespace/service/1", "ExtraError");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: de.drv.dsrv.spoc.extra.v1_3.jaxb.service
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ExtraErrorType }
     * 
     */
    public ExtraErrorType createExtraErrorType() {
        return new ExtraErrorType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExtraErrorType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.extra-standard.de/namespace/service/1", name = "ExtraError")
    public JAXBElement<ExtraErrorType> createExtraError(ExtraErrorType value) {
        return new JAXBElement<ExtraErrorType>(_ExtraError_QNAME, ExtraErrorType.class, null, value);
    }

}
