//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.24 at 11:30:02 AM CEST 
//


package de.drv.dsrv.spoc.extra.v1_3.jaxb.response;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;
import de.drv.dsrv.spoc.extra.v1_3.jaxb.components.AnyPlugInContainerType;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the de.drv.dsrv.spoc.extra.v1_3.jaxb.response package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _PackageHeader_QNAME = new QName("http://www.extra-standard.de/namespace/response/1", "PackageHeader");
    private final static QName _MessageBody_QNAME = new QName("http://www.extra-standard.de/namespace/response/1", "MessageBody");
    private final static QName _XMLTransport_QNAME = new QName("http://www.extra-standard.de/namespace/response/1", "XMLTransport");
    private final static QName _TransportBody_QNAME = new QName("http://www.extra-standard.de/namespace/response/1", "TransportBody");
    private final static QName _TransportPlugIns_QNAME = new QName("http://www.extra-standard.de/namespace/response/1", "TransportPlugIns");
    private final static QName _Transport_QNAME = new QName("http://www.extra-standard.de/namespace/response/1", "Transport");
    private final static QName _MessagePlugIns_QNAME = new QName("http://www.extra-standard.de/namespace/response/1", "MessagePlugIns");
    private final static QName _MessageHeader_QNAME = new QName("http://www.extra-standard.de/namespace/response/1", "MessageHeader");
    private final static QName _TransportHeader_QNAME = new QName("http://www.extra-standard.de/namespace/response/1", "TransportHeader");
    private final static QName _PackageBody_QNAME = new QName("http://www.extra-standard.de/namespace/response/1", "PackageBody");
    private final static QName _PackagePlugIns_QNAME = new QName("http://www.extra-standard.de/namespace/response/1", "PackagePlugIns");
    private final static QName _Package_QNAME = new QName("http://www.extra-standard.de/namespace/response/1", "Package");
    private final static QName _Message_QNAME = new QName("http://www.extra-standard.de/namespace/response/1", "Message");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: de.drv.dsrv.spoc.extra.v1_3.jaxb.response
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PackageResponseType }
     * 
     */
    public PackageResponseType createPackageResponseType() {
        return new PackageResponseType();
    }

    /**
     * Create an instance of {@link MessageResponseType }
     * 
     */
    public MessageResponseType createMessageResponseType() {
        return new MessageResponseType();
    }

    /**
     * Create an instance of {@link PackageResponseBodyType }
     * 
     */
    public PackageResponseBodyType createPackageResponseBodyType() {
        return new PackageResponseBodyType();
    }

    /**
     * Create an instance of {@link TransportResponseType }
     * 
     */
    public TransportResponseType createTransportResponseType() {
        return new TransportResponseType();
    }

    /**
     * Create an instance of {@link MessageResponseBodyType }
     * 
     */
    public MessageResponseBodyType createMessageResponseBodyType() {
        return new MessageResponseBodyType();
    }

    /**
     * Create an instance of {@link TransportResponseBodyType }
     * 
     */
    public TransportResponseBodyType createTransportResponseBodyType() {
        return new TransportResponseBodyType();
    }

    /**
     * Create an instance of {@link PackageResponseHeaderType }
     * 
     */
    public PackageResponseHeaderType createPackageResponseHeaderType() {
        return new PackageResponseHeaderType();
    }

    /**
     * Create an instance of {@link MessageResponseHeaderType }
     * 
     */
    public MessageResponseHeaderType createMessageResponseHeaderType() {
        return new MessageResponseHeaderType();
    }

    /**
     * Create an instance of {@link TransportResponseHeaderType }
     * 
     */
    public TransportResponseHeaderType createTransportResponseHeaderType() {
        return new TransportResponseHeaderType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PackageResponseHeaderType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.extra-standard.de/namespace/response/1", name = "PackageHeader")
    public JAXBElement<PackageResponseHeaderType> createPackageHeader(PackageResponseHeaderType value) {
        return new JAXBElement<PackageResponseHeaderType>(_PackageHeader_QNAME, PackageResponseHeaderType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MessageResponseBodyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.extra-standard.de/namespace/response/1", name = "MessageBody")
    public JAXBElement<MessageResponseBodyType> createMessageBody(MessageResponseBodyType value) {
        return new JAXBElement<MessageResponseBodyType>(_MessageBody_QNAME, MessageResponseBodyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TransportResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.extra-standard.de/namespace/response/1", name = "XMLTransport")
    public JAXBElement<TransportResponseType> createXMLTransport(TransportResponseType value) {
        return new JAXBElement<TransportResponseType>(_XMLTransport_QNAME, TransportResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TransportResponseBodyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.extra-standard.de/namespace/response/1", name = "TransportBody")
    public JAXBElement<TransportResponseBodyType> createTransportBody(TransportResponseBodyType value) {
        return new JAXBElement<TransportResponseBodyType>(_TransportBody_QNAME, TransportResponseBodyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AnyPlugInContainerType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.extra-standard.de/namespace/response/1", name = "TransportPlugIns")
    public JAXBElement<AnyPlugInContainerType> createTransportPlugIns(AnyPlugInContainerType value) {
        return new JAXBElement<AnyPlugInContainerType>(_TransportPlugIns_QNAME, AnyPlugInContainerType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TransportResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.extra-standard.de/namespace/response/1", name = "Transport")
    public JAXBElement<TransportResponseType> createTransport(TransportResponseType value) {
        return new JAXBElement<TransportResponseType>(_Transport_QNAME, TransportResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AnyPlugInContainerType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.extra-standard.de/namespace/response/1", name = "MessagePlugIns")
    public JAXBElement<AnyPlugInContainerType> createMessagePlugIns(AnyPlugInContainerType value) {
        return new JAXBElement<AnyPlugInContainerType>(_MessagePlugIns_QNAME, AnyPlugInContainerType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MessageResponseHeaderType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.extra-standard.de/namespace/response/1", name = "MessageHeader")
    public JAXBElement<MessageResponseHeaderType> createMessageHeader(MessageResponseHeaderType value) {
        return new JAXBElement<MessageResponseHeaderType>(_MessageHeader_QNAME, MessageResponseHeaderType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TransportResponseHeaderType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.extra-standard.de/namespace/response/1", name = "TransportHeader")
    public JAXBElement<TransportResponseHeaderType> createTransportHeader(TransportResponseHeaderType value) {
        return new JAXBElement<TransportResponseHeaderType>(_TransportHeader_QNAME, TransportResponseHeaderType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PackageResponseBodyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.extra-standard.de/namespace/response/1", name = "PackageBody")
    public JAXBElement<PackageResponseBodyType> createPackageBody(PackageResponseBodyType value) {
        return new JAXBElement<PackageResponseBodyType>(_PackageBody_QNAME, PackageResponseBodyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AnyPlugInContainerType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.extra-standard.de/namespace/response/1", name = "PackagePlugIns")
    public JAXBElement<AnyPlugInContainerType> createPackagePlugIns(AnyPlugInContainerType value) {
        return new JAXBElement<AnyPlugInContainerType>(_PackagePlugIns_QNAME, AnyPlugInContainerType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PackageResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.extra-standard.de/namespace/response/1", name = "Package")
    public JAXBElement<PackageResponseType> createPackage(PackageResponseType value) {
        return new JAXBElement<PackageResponseType>(_Package_QNAME, PackageResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MessageResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.extra-standard.de/namespace/response/1", name = "Message")
    public JAXBElement<MessageResponseType> createMessage(MessageResponseType value) {
        return new JAXBElement<MessageResponseType>(_Message_QNAME, MessageResponseType.class, null, value);
    }

}
