//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.24 at 11:30:02 AM CEST 
//


package de.drv.dsrv.spoc.extra.v1_3.jaxb.logging;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import de.drv.dsrv.spoc.extra.v1_3.jaxb.components.AnyXMLType;


/**
 * <p>Java class for LogStreamType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LogStreamType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.extra-standard.de/namespace/components/1}TimeStamp"/>
 *         &lt;element ref="{http://www.extra-standard.de/namespace/components/1}ComponentID" minOccurs="0"/>
 *         &lt;element ref="{http://www.extra-standard.de/namespace/components/1}ProcessID" minOccurs="0"/>
 *         &lt;element ref="{http://www.extra-standard.de/namespace/logging/1}LogTrace" minOccurs="0"/>
 *         &lt;element ref="{http://www.extra-standard.de/namespace/components/1}AnyXML" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LogStreamType", propOrder = {
    "timeStamp",
    "componentID",
    "processID",
    "logTrace",
    "anyXML"
})
public class LogStreamType implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "TimeStamp", namespace = "http://www.extra-standard.de/namespace/components/1", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar timeStamp;
    @XmlElement(name = "ComponentID", namespace = "http://www.extra-standard.de/namespace/components/1")
    protected String componentID;
    @XmlElement(name = "ProcessID", namespace = "http://www.extra-standard.de/namespace/components/1")
    protected String processID;
    @XmlElement(name = "LogTrace")
    protected LogTraceType logTrace;
    @XmlElement(name = "AnyXML", namespace = "http://www.extra-standard.de/namespace/components/1", required = true)
    protected List<AnyXMLType> anyXML;

    /**
     * Gets the value of the timeStamp property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTimeStamp() {
        return timeStamp;
    }

    /**
     * Sets the value of the timeStamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTimeStamp(XMLGregorianCalendar value) {
        this.timeStamp = value;
    }

    /**
     * Gets the value of the componentID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComponentID() {
        return componentID;
    }

    /**
     * Sets the value of the componentID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComponentID(String value) {
        this.componentID = value;
    }

    /**
     * Gets the value of the processID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcessID() {
        return processID;
    }

    /**
     * Sets the value of the processID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcessID(String value) {
        this.processID = value;
    }

    /**
     * Gets the value of the logTrace property.
     * 
     * @return
     *     possible object is
     *     {@link LogTraceType }
     *     
     */
    public LogTraceType getLogTrace() {
        return logTrace;
    }

    /**
     * Sets the value of the logTrace property.
     * 
     * @param value
     *     allowed object is
     *     {@link LogTraceType }
     *     
     */
    public void setLogTrace(LogTraceType value) {
        this.logTrace = value;
    }

    /**
     * Gets the value of the anyXML property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the anyXML property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAnyXML().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AnyXMLType }
     * 
     * 
     */
    public List<AnyXMLType> getAnyXML() {
        if (anyXML == null) {
            anyXML = new ArrayList<AnyXMLType>();
        }
        return this.anyXML;
    }

}
