//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.24 at 11:30:02 AM CEST 
//


package de.drv.dsrv.spoc.extra.v1_3.jaxb.logging;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import de.drv.dsrv.spoc.extra.v1_3.jaxb.components.PropertyType;
import de.drv.dsrv.spoc.extra.v1_3.jaxb.components.XMLFragmentType;


/**
 * <p>Java class for StateType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StateType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.extra-standard.de/namespace/components/1}TimeStamp"/>
 *         &lt;choice>
 *           &lt;element ref="{http://www.extra-standard.de/namespace/components/1}Property"/>
 *           &lt;element ref="{http://www.extra-standard.de/namespace/components/1}XMLFragment"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StateType", propOrder = {
    "timeStamp",
    "property",
    "xmlFragment"
})
public class StateType implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "TimeStamp", namespace = "http://www.extra-standard.de/namespace/components/1", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar timeStamp;
    @XmlElement(name = "Property", namespace = "http://www.extra-standard.de/namespace/components/1")
    protected PropertyType property;
    @XmlElement(name = "XMLFragment", namespace = "http://www.extra-standard.de/namespace/components/1")
    protected XMLFragmentType xmlFragment;

    /**
     * Gets the value of the timeStamp property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTimeStamp() {
        return timeStamp;
    }

    /**
     * Sets the value of the timeStamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTimeStamp(XMLGregorianCalendar value) {
        this.timeStamp = value;
    }

    /**
     * Gets the value of the property property.
     * 
     * @return
     *     possible object is
     *     {@link PropertyType }
     *     
     */
    public PropertyType getProperty() {
        return property;
    }

    /**
     * Sets the value of the property property.
     * 
     * @param value
     *     allowed object is
     *     {@link PropertyType }
     *     
     */
    public void setProperty(PropertyType value) {
        this.property = value;
    }

    /**
     * Gets the value of the xmlFragment property.
     * 
     * @return
     *     possible object is
     *     {@link XMLFragmentType }
     *     
     */
    public XMLFragmentType getXMLFragment() {
        return xmlFragment;
    }

    /**
     * Sets the value of the xmlFragment property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLFragmentType }
     *     
     */
    public void setXMLFragment(XMLFragmentType value) {
        this.xmlFragment = value;
    }

}
