//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.24 at 11:30:02 AM CEST 
//


package de.drv.dsrv.spoc.extra.v1_3.jaxb.messages;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EventNamesType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="EventNamesType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyURI">
 *     &lt;enumeration value="http://www.extra-standard.de/event/Default"/>
 *     &lt;enumeration value="http://www.extra-standard.de/event/SendData"/>
 *     &lt;enumeration value="http://www.extra-standard.de/event/RequestData"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "EventNamesType")
@XmlEnum
public enum EventNamesType {

    @XmlEnumValue("http://www.extra-standard.de/event/Default")
    Default("http://www.extra-standard.de/event/Default"),
    @XmlEnumValue("http://www.extra-standard.de/event/SendData")
    SendData("http://www.extra-standard.de/event/SendData"),
    @XmlEnumValue("http://www.extra-standard.de/event/RequestData")
    RequestData("http://www.extra-standard.de/event/RequestData");
    private final String value;

    EventNamesType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static EventNamesType fromValue(String v) {
        for (EventNamesType c: EventNamesType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
