//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.24 at 11:30:02 AM CEST 
//


package de.drv.dsrv.spoc.extra.v1_3.jaxb.messages;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ExtraLayerNamesType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ExtraLayerNamesType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyURI">
 *     &lt;enumeration value="http://www.extra-standard.de/layer/Transport"/>
 *     &lt;enumeration value="http://www.extra-standard.de/layer/Package"/>
 *     &lt;enumeration value="http://www.extra-standard.de/layer/Message"/>
 *     &lt;enumeration value="http://www.extra-standard.de/layer/Application"/>
 *     &lt;enumeration value="http://www.extra-standard.de/layer/Delivery"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ExtraLayerNamesType")
@XmlEnum
public enum ExtraLayerNamesType {

    @XmlEnumValue("http://www.extra-standard.de/layer/Transport")
    Transport("http://www.extra-standard.de/layer/Transport"),
    @XmlEnumValue("http://www.extra-standard.de/layer/Package")
    Package("http://www.extra-standard.de/layer/Package"),
    @XmlEnumValue("http://www.extra-standard.de/layer/Message")
    Message("http://www.extra-standard.de/layer/Message"),
    @XmlEnumValue("http://www.extra-standard.de/layer/Application")
    Application("http://www.extra-standard.de/layer/Application"),
    @XmlEnumValue("http://www.extra-standard.de/layer/Delivery")
    Delivery("http://www.extra-standard.de/layer/Delivery");
    private final String value;

    ExtraLayerNamesType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ExtraLayerNamesType fromValue(String v) {
        for (ExtraLayerNamesType c: ExtraLayerNamesType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
