//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.24 at 11:30:02 AM CEST 
//


package de.drv.dsrv.spoc.extra.v1_3.jaxb.messages;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ListOfStatusResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ListOfStatusResponseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="StatusResponse">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Property" type="{http://www.extra-standard.de/namespace/message/1}StatusResponsePropertyType"/>
 *                   &lt;element name="Trace" type="{http://www.extra-standard.de/namespace/message/1}TraceType"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="version" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="1.0"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ListOfStatusResponseType", propOrder = {
    "statusResponse"
})
public class ListOfStatusResponseType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "StatusResponse", required = true)
    protected ListOfStatusResponseType.StatusResponse statusResponse;
    @XmlAttribute(name = "version", required = true)
    protected String version;

    /**
     * Gets the value of the statusResponse property.
     * 
     * @return
     *     possible object is
     *     {@link ListOfStatusResponseType.StatusResponse }
     *     
     */
    public ListOfStatusResponseType.StatusResponse getStatusResponse() {
        return statusResponse;
    }

    /**
     * Sets the value of the statusResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListOfStatusResponseType.StatusResponse }
     *     
     */
    public void setStatusResponse(ListOfStatusResponseType.StatusResponse value) {
        this.statusResponse = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Property" type="{http://www.extra-standard.de/namespace/message/1}StatusResponsePropertyType"/>
     *         &lt;element name="Trace" type="{http://www.extra-standard.de/namespace/message/1}TraceType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "property",
        "trace"
    })
    public static class StatusResponse
        implements Serializable
    {

        private final static long serialVersionUID = 1L;
        @XmlElement(name = "Property", required = true)
        protected StatusResponsePropertyType property;
        @XmlElement(name = "Trace", required = true)
        protected TraceType trace;

        /**
         * Gets the value of the property property.
         * 
         * @return
         *     possible object is
         *     {@link StatusResponsePropertyType }
         *     
         */
        public StatusResponsePropertyType getProperty() {
            return property;
        }

        /**
         * Sets the value of the property property.
         * 
         * @param value
         *     allowed object is
         *     {@link StatusResponsePropertyType }
         *     
         */
        public void setProperty(StatusResponsePropertyType value) {
            this.property = value;
        }

        /**
         * Gets the value of the trace property.
         * 
         * @return
         *     possible object is
         *     {@link TraceType }
         *     
         */
        public TraceType getTrace() {
            return trace;
        }

        /**
         * Sets the value of the trace property.
         * 
         * @param value
         *     allowed object is
         *     {@link TraceType }
         *     
         */
        public void setTrace(TraceType value) {
            this.trace = value;
        }

    }

}
