//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.24 at 11:30:02 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.extra-standard.de/namespace/message/1", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package de.drv.dsrv.spoc.extra.v1_3.jaxb.messages;
