//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.24 at 11:30:02 AM CEST 
//


package de.drv.dsrv.spoc.extra.v1_3.jaxb.messages;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for StatusNamesType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="StatusNamesType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyURI">
 *     &lt;enumeration value="http://www.extra-standard.de/status/ACCEPTED"/>
 *     &lt;enumeration value="http://www.extra-standard.de/status/PROCESSING"/>
 *     &lt;enumeration value="http://www.extra-standard.de/status/COMPLETED"/>
 *     &lt;enumeration value="http://www.extra-standard.de/status/CONFIRMED"/>
 *     &lt;enumeration value="http://www.extra-standard.de/status/FAILED"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "StatusNamesType")
@XmlEnum
public enum StatusNamesType {

    @XmlEnumValue("http://www.extra-standard.de/status/ACCEPTED")
    ACCEPTED("http://www.extra-standard.de/status/ACCEPTED"),
    @XmlEnumValue("http://www.extra-standard.de/status/PROCESSING")
    PROCESSING("http://www.extra-standard.de/status/PROCESSING"),
    @XmlEnumValue("http://www.extra-standard.de/status/COMPLETED")
    COMPLETED("http://www.extra-standard.de/status/COMPLETED"),
    @XmlEnumValue("http://www.extra-standard.de/status/CONFIRMED")
    CONFIRMED("http://www.extra-standard.de/status/CONFIRMED"),
    @XmlEnumValue("http://www.extra-standard.de/status/FAILED")
    FAILED("http://www.extra-standard.de/status/FAILED");
    private final String value;

    StatusNamesType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static StatusNamesType fromValue(String v) {
        for (StatusNamesType c: StatusNamesType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
