-- Generated by Oracle SQL Developer Data Modeler 3.0.0.665
--   at:        2012-09-24 11:35:27 MESZ
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



DROP TABLE EXECUTION CASCADE CONSTRAINTS 
;
DROP TABLE INPUT_DATA CASCADE CONSTRAINTS 
;
DROP TABLE INPUT_DATA_TRANSITION CASCADE CONSTRAINTS 
;
DROP TABLE MANDATOR CASCADE CONSTRAINTS 
;
DROP TABLE PROCEDURE CASCADE CONSTRAINTS 
;
DROP TABLE PROCEDURE_PHASE_CONFIGURATION CASCADE CONSTRAINTS 
;
DROP TABLE PROCEDURE_TYPE CASCADE CONSTRAINTS 
;
DROP TABLE STATUS CASCADE CONSTRAINTS 
;
CREATE TABLE EXECUTION 
    ( 
     id NUMBER (15)  NOT NULL , 
     start_time DATE  NOT NULL , 
     end_time DATE , 
     parameters CLOB , 
     procedure_id NUMBER (15)  NOT NULL , 
     status_id NUMBER (10)  NOT NULL 
    ) LOGGING 
;



ALTER TABLE EXECUTION 
    ADD CONSTRAINT execution_PK PRIMARY KEY ( id ) ;


CREATE TABLE INPUT_DATA 
    ( 
     id NUMBER (15)  NOT NULL , 
     input_identifier VARCHAR2 (255)  NOT NULL , 
     hashcode VARCHAR2 (100) , 
     error_code VARCHAR2 (255) , 
     error_message CLOB , 
     responseId VARCHAR2 (255) , 
     execution_id NUMBER (15)  NOT NULL , 
     last_transition_id NUMBER (15) 
    ) LOGGING 
;


CREATE INDEX INPUT_DATA_IDX_TRANSITION ON INPUT_DATA 
    ( 
     last_transition_id ASC 
    ) 
    LOGGING 
    NOCOMPRESS 
    NOPARALLEL 
;
CREATE INDEX INPUT_DATA__IDX_EXECUTION ON INPUT_DATA 
    ( 
     execution_id ASC 
    ) 
    LOGGING 
    NOCOMPRESS 
    NOPARALLEL 
;

ALTER TABLE INPUT_DATA 
    ADD CONSTRAINT input_data_PK PRIMARY KEY ( id ) ;


CREATE TABLE INPUT_DATA_TRANSITION 
    ( 
     id NUMBER (15)  NOT NULL , 
     transition_date DATE  NOT NULL , 
     duration NUMBER (8) , 
     input_data_id NUMBER (15)  NOT NULL , 
     current_status_id NUMBER (10)  NOT NULL , 
     prev_status_id NUMBER (10) 
    ) LOGGING 
;


CREATE INDEX TRANSITION_IDX_STATUS_DATE ON INPUT_DATA_TRANSITION 
    ( 
     current_status_id ASC , 
     transition_date ASC 
    ) 
    LOGGING 
    NOCOMPRESS 
    NOPARALLEL 
;

ALTER TABLE INPUT_DATA_TRANSITION 
    ADD CONSTRAINT INPUT_DATA_TRANSITION_PK PRIMARY KEY ( id ) ;


CREATE TABLE MANDATOR 
    ( 
     id NUMBER (15)  NOT NULL , 
     name VARCHAR2 (250 CHAR) 
    ) LOGGING 
;



ALTER TABLE MANDATOR 
    ADD CONSTRAINT "mandant PK" PRIMARY KEY ( id ) ;

ALTER TABLE MANDATOR 
    ADD CONSTRAINT mandant_un_name UNIQUE ( name ) ;


CREATE TABLE PROCEDURE 
    ( 
     id NUMBER (15)  NOT NULL , 
     name VARCHAR2 (255 CHAR)  NOT NULL , 
     mandator_id NUMBER (15)  NOT NULL , 
     procedure_type_id NUMBER (10)  NOT NULL 
    ) LOGGING 
;



ALTER TABLE PROCEDURE 
    ADD CONSTRAINT "procedure PK" PRIMARY KEY ( id ) ;

ALTER TABLE PROCEDURE 
    ADD CONSTRAINT procedure_un_name UNIQUE ( name ) ;


CREATE TABLE PROCEDURE_PHASE_CONFIGURATION 
    ( 
     id NUMBER (10)  NOT NULL , 
     phase VARCHAR2 (100)  NOT NULL , 
     phase_endstatus_id NUMBER (10)  NOT NULL , 
     procedure_type_id NUMBER (10)  NOT NULL 
    ) LOGGING 
;



ALTER TABLE PROCEDURE_PHASE_CONFIGURATION 
    ADD CONSTRAINT PROC_PHASE_CONFIG_PK PRIMARY KEY ( id ) ;


CREATE TABLE PROCEDURE_TYPE 
    ( 
     id NUMBER (10)  NOT NULL , 
     name VARCHAR2 (100) , 
     end_status_id NUMBER (10)  NOT NULL 
    ) LOGGING 
;



ALTER TABLE PROCEDURE_TYPE 
    ADD CONSTRAINT PROCEDURE_TYPE_PK PRIMARY KEY ( id ) ;


CREATE TABLE STATUS 
    ( 
     id NUMBER (10)  NOT NULL , 
     name VARCHAR2 (50)  NOT NULL 
    ) LOGGING 
;


CREATE INDEX STATUS_IDX_NAME ON STATUS 
    ( 
     name ASC 
    ) 
    LOGGING 
    NOCOMPRESS 
    NOPARALLEL 
;

ALTER TABLE STATUS 
    ADD CONSTRAINT status_PK PRIMARY KEY ( id ) ;



ALTER TABLE INPUT_DATA_TRANSITION 
    ADD CONSTRAINT REL_TRANSITION_CURR_STATUS FOREIGN KEY 
    ( 
     current_status_id
    ) 
    REFERENCES STATUS 
    ( 
     id
    ) 
    NOT DEFERRABLE 
;


ALTER TABLE INPUT_DATA_TRANSITION 
    ADD CONSTRAINT REL_TRANSITION_INPUT_DATA FOREIGN KEY 
    ( 
     input_data_id
    ) 
    REFERENCES INPUT_DATA 
    ( 
     id
    ) 
    NOT DEFERRABLE 
;


ALTER TABLE INPUT_DATA_TRANSITION 
    ADD CONSTRAINT REL_TRANSITION_PREV_STATUS FOREIGN KEY 
    ( 
     prev_status_id
    ) 
    REFERENCES STATUS 
    ( 
     id
    ) 
    NOT DEFERRABLE 
;


ALTER TABLE PROCEDURE_TYPE 
    ADD CONSTRAINT procedure_conf_endstatus_fk FOREIGN KEY 
    ( 
     end_status_id
    ) 
    REFERENCES STATUS 
    ( 
     id
    ) 
    NOT DEFERRABLE 
;


ALTER TABLE EXECUTION 
    ADD CONSTRAINT rel_execution_procedure FOREIGN KEY 
    ( 
     procedure_id
    ) 
    REFERENCES PROCEDURE 
    ( 
     id
    ) 
    NOT DEFERRABLE 
;


ALTER TABLE EXECUTION 
    ADD CONSTRAINT rel_execution_status FOREIGN KEY 
    ( 
     status_id
    ) 
    REFERENCES STATUS 
    ( 
     id
    ) 
    NOT DEFERRABLE 
;


ALTER TABLE INPUT_DATA 
    ADD CONSTRAINT rel_input_data_execution FOREIGN KEY 
    ( 
     execution_id
    ) 
    REFERENCES EXECUTION 
    ( 
     id
    ) 
    NOT DEFERRABLE 
;


ALTER TABLE INPUT_DATA 
    ADD CONSTRAINT rel_input_data_transition FOREIGN KEY 
    ( 
     last_transition_id
    ) 
    REFERENCES INPUT_DATA_TRANSITION 
    ( 
     id
    ) 
    ON DELETE SET NULL 
    NOT DEFERRABLE 
;


ALTER TABLE PROCEDURE_PHASE_CONFIGURATION 
    ADD CONSTRAINT rel_proc_configuration_status FOREIGN KEY 
    ( 
     phase_endstatus_id
    ) 
    REFERENCES STATUS 
    ( 
     id
    ) 
    NOT DEFERRABLE 
;


ALTER TABLE PROCEDURE_PHASE_CONFIGURATION 
    ADD CONSTRAINT rel_proc_phase_proc_config_pk FOREIGN KEY 
    ( 
     procedure_type_id
    ) 
    REFERENCES PROCEDURE_TYPE 
    ( 
     id
    ) 
    NOT DEFERRABLE 
;


ALTER TABLE PROCEDURE 
    ADD CONSTRAINT rel_proc_to_proc_config_pk FOREIGN KEY 
    ( 
     procedure_type_id
    ) 
    REFERENCES PROCEDURE_TYPE 
    ( 
     id
    ) 
    NOT DEFERRABLE 
;


ALTER TABLE PROCEDURE 
    ADD CONSTRAINT rel_procedure_mandant FOREIGN KEY 
    ( 
     mandator_id
    ) 
    REFERENCES MANDATOR 
    ( 
     id
    ) 
    NOT DEFERRABLE 
;

CREATE SEQUENCE seq_execution_id 
    START WITH 1 
    INCREMENT BY 1 
    MAXVALUE 999999999999 
    MINVALUE 1 
    CACHE 100 
;

CREATE SEQUENCE seq_input_data_id 
    START WITH 1 
    INCREMENT BY 1 
    MAXVALUE 99999999999 
    MINVALUE 1 
    CACHE 1000 
;

CREATE SEQUENCE seq_input_data_transition_id 
    START WITH 1 
    INCREMENT BY 1 
    MAXVALUE 9999999999 
    MINVALUE 1 
    CACHE 1000 
;

CREATE SEQUENCE seq_mandator_id 
    START WITH 1 
    INCREMENT BY 1 
    MAXVALUE 9999999 
    MINVALUE 1 
    CACHE 10 
;

CREATE SEQUENCE seq_procedure_id 
    START WITH 1 
    INCREMENT BY 1 
    MAXVALUE 9999999 
    MINVALUE 1 
    CACHE 10 
;

CREATE SEQUENCE seq_procedure_type_id 
    START WITH 1 
    INCREMENT BY 1 
    MAXVALUE 99999 
    MINVALUE 1 
    CACHE 10 
;

CREATE SEQUENCE seq_procephase_config_id 
    START WITH 1 
    INCREMENT BY 1 
    MAXVALUE 99999 
    MINVALUE 1 
    CACHE 10 
;

CREATE SEQUENCE seq_status_id 
    START WITH 1 
    INCREMENT BY 1 
    MAXVALUE 9999999 
    MINVALUE 1 
    CACHE 10 
    ORDER 
;











-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             8
-- CREATE INDEX                             4
-- ALTER TABLE                             22
-- CREATE VIEW                              0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- CREATE STRUCTURED TYPE                   0
-- CREATE COLLECTION TYPE                   0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          8
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
