package de.extra_standard.namespace.webservice;

import javax.xml.ws.WebFault;

import de.drv.dsrv.extrastandard.namespace.error.Error;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.5-b03- Generated
 * source version: 2.1
 * 
 */
@WebFault(name = "ExtraError", targetNamespace = "http://www.extra-standard.de/namespace/service/1")
public class ExtraFault extends Exception {

	/**
	 * Java type that goes as soapenv:Fault detail element.
	 * 
	 */
	private final Error faultInfo;

	/**
	 * 
	 * @param message
	 * @param faultInfo
	 */
	public ExtraFault(final String message, final Error faultInfo) {
		super(message);
		this.faultInfo = faultInfo;
	}

	/**
	 * 
	 * @param message
	 * @param faultInfo
	 * @param cause
	 */
	public ExtraFault(final String message, final Error faultInfo,
			final Throwable cause) {
		super(message, cause);
		this.faultInfo = faultInfo;
	}

	/**
	 * 
	 * @return returns fault bean:
	 *         de.extra_standard.namespace.service._1.ExtraErrorType
	 */
	public Error getFaultInfo() {
		return faultInfo;
	}

}
