/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-11/13/2008 12:46 PM(foreman)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.08.30 at 03:14:38 PM CEST 
//
package de.extra.client.plugins.dataplugin.auftragssatz;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for dataSourceInfoType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="dataSourceInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}dsType"/>
 *         &lt;element ref="{}dsName"/>
 *         &lt;element ref="{}dsCreateDate"/>
 *         &lt;element ref="{}dsEncoding"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "dataSourceInfoType", propOrder = { "dsType", "dsName",
		"dsCreateDate", "dsEncoding" })
public class DataSourceInfoType {

	@XmlElement(required = true)
	protected String dsType;
	@XmlElement(required = true)
	protected String dsName;
	@XmlElement(required = true)
	protected XMLGregorianCalendar dsCreateDate;
	@XmlElement(required = true)
	protected String dsEncoding;

	/**
	 * Gets the value of the dsType property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDsType() {
		return dsType;
	}

	/**
	 * Sets the value of the dsType property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDsType(String value) {
		this.dsType = value;
	}

	/**
	 * Gets the value of the dsName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDsName() {
		return dsName;
	}

	/**
	 * Sets the value of the dsName property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDsName(String value) {
		this.dsName = value;
	}

	/**
	 * Gets the value of the dsCreateDate property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 * 
	 */
	public XMLGregorianCalendar getDsCreateDate() {
		return dsCreateDate;
	}

	/**
	 * Sets the value of the dsCreateDate property.
	 * 
	 * @param value
	 *            allowed object is {@link XMLGregorianCalendar }
	 * 
	 */
	public void setDsCreateDate(XMLGregorianCalendar value) {
		this.dsCreateDate = value;
	}

	/**
	 * Gets the value of the dsEncoding property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDsEncoding() {
		return dsEncoding;
	}

	/**
	 * Sets the value of the dsEncoding property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDsEncoding(String value) {
		this.dsEncoding = value;
	}
}
