//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.24 at 11:30:02 AM CEST 
//


package de.drv.dsrv.spoc.extra.v1_3.jaxb.response;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import de.drv.dsrv.spoc.extra.v1_3.jaxb.components.AnyPlugInContainerType;
import de.drv.dsrv.spoc.extra.v1_3.jaxb.components.ElementWithOptionalVersionType;
import de.drv.dsrv.spoc.extra.v1_3.jaxb.components.SignaturesType;
import de.drv.dsrv.spoc.extra.v1_3.jaxb.logging.LoggingType;


/**
 * <p>Java class for MessageResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MessageResponseType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.extra-standard.de/namespace/components/1}ElementWithOptionalVersionType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.extra-standard.de/namespace/response/1}MessageHeader"/>
 *         &lt;element ref="{http://www.extra-standard.de/namespace/response/1}MessagePlugIns" minOccurs="0"/>
 *         &lt;element ref="{http://www.extra-standard.de/namespace/response/1}MessageBody"/>
 *         &lt;element ref="{http://www.extra-standard.de/namespace/logging/1}Logging" minOccurs="0"/>
 *         &lt;element ref="{http://www.extra-standard.de/namespace/components/1}Signatures" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MessageResponseType", propOrder = {
    "messageHeader",
    "messagePlugIns",
    "messageBody",
    "logging",
    "signatures"
})
public class MessageResponseType
    extends ElementWithOptionalVersionType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "MessageHeader", required = true)
    protected MessageResponseHeaderType messageHeader;
    @XmlElement(name = "MessagePlugIns")
    protected AnyPlugInContainerType messagePlugIns;
    @XmlElement(name = "MessageBody", required = true)
    protected MessageResponseBodyType messageBody;
    @XmlElement(name = "Logging", namespace = "http://www.extra-standard.de/namespace/logging/1")
    protected LoggingType logging;
    @XmlElement(name = "Signatures", namespace = "http://www.extra-standard.de/namespace/components/1")
    protected SignaturesType signatures;

    /**
     * Gets the value of the messageHeader property.
     * 
     * @return
     *     possible object is
     *     {@link MessageResponseHeaderType }
     *     
     */
    public MessageResponseHeaderType getMessageHeader() {
        return messageHeader;
    }

    /**
     * Sets the value of the messageHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link MessageResponseHeaderType }
     *     
     */
    public void setMessageHeader(MessageResponseHeaderType value) {
        this.messageHeader = value;
    }

    /**
     * Gets the value of the messagePlugIns property.
     * 
     * @return
     *     possible object is
     *     {@link AnyPlugInContainerType }
     *     
     */
    public AnyPlugInContainerType getMessagePlugIns() {
        return messagePlugIns;
    }

    /**
     * Sets the value of the messagePlugIns property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnyPlugInContainerType }
     *     
     */
    public void setMessagePlugIns(AnyPlugInContainerType value) {
        this.messagePlugIns = value;
    }

    /**
     * Gets the value of the messageBody property.
     * 
     * @return
     *     possible object is
     *     {@link MessageResponseBodyType }
     *     
     */
    public MessageResponseBodyType getMessageBody() {
        return messageBody;
    }

    /**
     * Sets the value of the messageBody property.
     * 
     * @param value
     *     allowed object is
     *     {@link MessageResponseBodyType }
     *     
     */
    public void setMessageBody(MessageResponseBodyType value) {
        this.messageBody = value;
    }

    /**
     * Gets the value of the logging property.
     * 
     * @return
     *     possible object is
     *     {@link LoggingType }
     *     
     */
    public LoggingType getLogging() {
        return logging;
    }

    /**
     * Sets the value of the logging property.
     * 
     * @param value
     *     allowed object is
     *     {@link LoggingType }
     *     
     */
    public void setLogging(LoggingType value) {
        this.logging = value;
    }

    /**
     * Gets the value of the signatures property.
     * 
     * @return
     *     possible object is
     *     {@link SignaturesType }
     *     
     */
    public SignaturesType getSignatures() {
        return signatures;
    }

    /**
     * Sets the value of the signatures property.
     * 
     * @param value
     *     allowed object is
     *     {@link SignaturesType }
     *     
     */
    public void setSignatures(SignaturesType value) {
        this.signatures = value;
    }

}
