//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.24 at 11:30:02 AM CEST 
//


package de.drv.dsrv.spoc.extra.v1_3.jaxb.response;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import de.drv.dsrv.spoc.extra.v1_3.jaxb.components.ElementWithOptionalVersionType;
import de.drv.dsrv.spoc.extra.v1_3.jaxb.components.ReceiverType;
import de.drv.dsrv.spoc.extra.v1_3.jaxb.components.RequestDetailsType;
import de.drv.dsrv.spoc.extra.v1_3.jaxb.components.ResponseDetailsType;
import de.drv.dsrv.spoc.extra.v1_3.jaxb.components.SenderType;


/**
 * <p>Java class for TransportResponseHeaderType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TransportResponseHeaderType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.extra-standard.de/namespace/components/1}ElementWithOptionalVersionType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.extra-standard.de/namespace/components/1}TestIndicator" minOccurs="0"/>
 *         &lt;element ref="{http://www.extra-standard.de/namespace/components/1}Sender"/>
 *         &lt;element ref="{http://www.extra-standard.de/namespace/components/1}Receiver"/>
 *         &lt;element ref="{http://www.extra-standard.de/namespace/components/1}RequestDetails"/>
 *         &lt;element ref="{http://www.extra-standard.de/namespace/components/1}ResponseDetails"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TransportResponseHeaderType", propOrder = {
    "testIndicator",
    "sender",
    "receiver",
    "requestDetails",
    "responseDetails"
})
public class TransportResponseHeaderType
    extends ElementWithOptionalVersionType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "TestIndicator", namespace = "http://www.extra-standard.de/namespace/components/1")
    protected String testIndicator;
    @XmlElement(name = "Sender", namespace = "http://www.extra-standard.de/namespace/components/1", required = true)
    protected SenderType sender;
    @XmlElement(name = "Receiver", namespace = "http://www.extra-standard.de/namespace/components/1", required = true)
    protected ReceiverType receiver;
    @XmlElement(name = "RequestDetails", namespace = "http://www.extra-standard.de/namespace/components/1", required = true)
    protected RequestDetailsType requestDetails;
    @XmlElement(name = "ResponseDetails", namespace = "http://www.extra-standard.de/namespace/components/1", required = true)
    protected ResponseDetailsType responseDetails;

    /**
     * Gets the value of the testIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTestIndicator() {
        return testIndicator;
    }

    /**
     * Sets the value of the testIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTestIndicator(String value) {
        this.testIndicator = value;
    }

    /**
     * Gets the value of the sender property.
     * 
     * @return
     *     possible object is
     *     {@link SenderType }
     *     
     */
    public SenderType getSender() {
        return sender;
    }

    /**
     * Sets the value of the sender property.
     * 
     * @param value
     *     allowed object is
     *     {@link SenderType }
     *     
     */
    public void setSender(SenderType value) {
        this.sender = value;
    }

    /**
     * Gets the value of the receiver property.
     * 
     * @return
     *     possible object is
     *     {@link ReceiverType }
     *     
     */
    public ReceiverType getReceiver() {
        return receiver;
    }

    /**
     * Sets the value of the receiver property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReceiverType }
     *     
     */
    public void setReceiver(ReceiverType value) {
        this.receiver = value;
    }

    /**
     * Gets the value of the requestDetails property.
     * 
     * @return
     *     possible object is
     *     {@link RequestDetailsType }
     *     
     */
    public RequestDetailsType getRequestDetails() {
        return requestDetails;
    }

    /**
     * Sets the value of the requestDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequestDetailsType }
     *     
     */
    public void setRequestDetails(RequestDetailsType value) {
        this.requestDetails = value;
    }

    /**
     * Gets the value of the responseDetails property.
     * 
     * @return
     *     possible object is
     *     {@link ResponseDetailsType }
     *     
     */
    public ResponseDetailsType getResponseDetails() {
        return responseDetails;
    }

    /**
     * Sets the value of the responseDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResponseDetailsType }
     *     
     */
    public void setResponseDetails(ResponseDetailsType value) {
        this.responseDetails = value;
    }

}
