//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.24 at 11:30:02 AM CEST 
//


package de.drv.dsrv.spoc.extra.v1_3.jaxb.response;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import de.drv.dsrv.spoc.extra.v1_3.jaxb.components.AnyPlugInContainerType;
import de.drv.dsrv.spoc.extra.v1_3.jaxb.components.RootElementType;
import de.drv.dsrv.spoc.extra.v1_3.jaxb.components.SignaturesType;
import de.drv.dsrv.spoc.extra.v1_3.jaxb.logging.LoggingType;


/**
 * <p>Java class for TransportResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TransportResponseType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.extra-standard.de/namespace/components/1}RootElementType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.extra-standard.de/namespace/response/1}TransportHeader"/>
 *         &lt;element ref="{http://www.extra-standard.de/namespace/response/1}TransportPlugIns" minOccurs="0"/>
 *         &lt;element ref="{http://www.extra-standard.de/namespace/response/1}TransportBody"/>
 *         &lt;element ref="{http://www.extra-standard.de/namespace/logging/1}Logging" minOccurs="0"/>
 *         &lt;element ref="{http://www.extra-standard.de/namespace/components/1}Signatures" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TransportResponseType", propOrder = {
    "transportHeader",
    "transportPlugIns",
    "transportBody",
    "logging",
    "signatures"
})
@XmlRootElement(name = "Transport")
public class TransportResponseType
    extends RootElementType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "TransportHeader", required = true)
    protected TransportResponseHeaderType transportHeader;
    @XmlElement(name = "TransportPlugIns")
    protected AnyPlugInContainerType transportPlugIns;
    @XmlElement(name = "TransportBody", required = true)
    protected TransportResponseBodyType transportBody;
    @XmlElement(name = "Logging", namespace = "http://www.extra-standard.de/namespace/logging/1")
    protected LoggingType logging;
    @XmlElement(name = "Signatures", namespace = "http://www.extra-standard.de/namespace/components/1")
    protected SignaturesType signatures;

    /**
     * Gets the value of the transportHeader property.
     * 
     * @return
     *     possible object is
     *     {@link TransportResponseHeaderType }
     *     
     */
    public TransportResponseHeaderType getTransportHeader() {
        return transportHeader;
    }

    /**
     * Sets the value of the transportHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransportResponseHeaderType }
     *     
     */
    public void setTransportHeader(TransportResponseHeaderType value) {
        this.transportHeader = value;
    }

    /**
     * Gets the value of the transportPlugIns property.
     * 
     * @return
     *     possible object is
     *     {@link AnyPlugInContainerType }
     *     
     */
    public AnyPlugInContainerType getTransportPlugIns() {
        return transportPlugIns;
    }

    /**
     * Sets the value of the transportPlugIns property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnyPlugInContainerType }
     *     
     */
    public void setTransportPlugIns(AnyPlugInContainerType value) {
        this.transportPlugIns = value;
    }

    /**
     * Gets the value of the transportBody property.
     * 
     * @return
     *     possible object is
     *     {@link TransportResponseBodyType }
     *     
     */
    public TransportResponseBodyType getTransportBody() {
        return transportBody;
    }

    /**
     * Sets the value of the transportBody property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransportResponseBodyType }
     *     
     */
    public void setTransportBody(TransportResponseBodyType value) {
        this.transportBody = value;
    }

    /**
     * Gets the value of the logging property.
     * 
     * @return
     *     possible object is
     *     {@link LoggingType }
     *     
     */
    public LoggingType getLogging() {
        return logging;
    }

    /**
     * Sets the value of the logging property.
     * 
     * @param value
     *     allowed object is
     *     {@link LoggingType }
     *     
     */
    public void setLogging(LoggingType value) {
        this.logging = value;
    }

    /**
     * Gets the value of the signatures property.
     * 
     * @return
     *     possible object is
     *     {@link SignaturesType }
     *     
     */
    public SignaturesType getSignatures() {
        return signatures;
    }

    /**
     * Sets the value of the signatures property.
     * 
     * @param value
     *     allowed object is
     *     {@link SignaturesType }
     *     
     */
    public void setSignatures(SignaturesType value) {
        this.signatures = value;
    }

}
