//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.24 at 11:30:02 AM CEST 
//


package de.drv.dsrv.spoc.extra.v1_3.jaxb.components;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import de.drv.dsrv.spoc.extra.v1_3.jaxb.request.MessageRequestBodyType;
import de.drv.dsrv.spoc.extra.v1_3.jaxb.request.MessageRequestHeaderType;
import de.drv.dsrv.spoc.extra.v1_3.jaxb.request.MessageRequestType;
import de.drv.dsrv.spoc.extra.v1_3.jaxb.request.PackageRequestBodyType;
import de.drv.dsrv.spoc.extra.v1_3.jaxb.request.PackageRequestHeaderType;
import de.drv.dsrv.spoc.extra.v1_3.jaxb.request.PackageRequestType;
import de.drv.dsrv.spoc.extra.v1_3.jaxb.request.TransportRequestBodyType;
import de.drv.dsrv.spoc.extra.v1_3.jaxb.request.TransportRequestHeaderType;
import de.drv.dsrv.spoc.extra.v1_3.jaxb.response.MessageResponseBodyType;
import de.drv.dsrv.spoc.extra.v1_3.jaxb.response.MessageResponseHeaderType;
import de.drv.dsrv.spoc.extra.v1_3.jaxb.response.MessageResponseType;
import de.drv.dsrv.spoc.extra.v1_3.jaxb.response.PackageResponseBodyType;
import de.drv.dsrv.spoc.extra.v1_3.jaxb.response.PackageResponseHeaderType;
import de.drv.dsrv.spoc.extra.v1_3.jaxb.response.PackageResponseType;
import de.drv.dsrv.spoc.extra.v1_3.jaxb.response.TransportResponseBodyType;
import de.drv.dsrv.spoc.extra.v1_3.jaxb.response.TransportResponseHeaderType;


/**
 * <p>Java class for ElementWithOptionalVersionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ElementWithOptionalVersionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="version" type="{http://www.extra-standard.de/namespace/components/1}AbstractVersionType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ElementWithOptionalVersionType")
@XmlSeeAlso({
    PackageRequestType.class,
    MessageRequestType.class,
    PackageRequestBodyType.class,
    MessageRequestBodyType.class,
    TransportRequestBodyType.class,
    PackageRequestHeaderType.class,
    MessageRequestHeaderType.class,
    TransportRequestHeaderType.class,
    PackageResponseType.class,
    MessageResponseType.class,
    PackageResponseBodyType.class,
    MessageResponseBodyType.class,
    TransportResponseBodyType.class,
    PackageResponseHeaderType.class,
    MessageResponseHeaderType.class,
    TransportResponseHeaderType.class
})
public abstract class ElementWithOptionalVersionType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlAttribute(name = "version")
    protected String version;

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

}
