//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.24 at 11:30:02 AM CEST 
//


package de.drv.dsrv.spoc.extra.v1_3.jaxb.components;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SupportedVersionsType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="SupportedVersionsType">
 *   &lt;restriction base="{http://www.extra-standard.de/namespace/components/1}AbstractVersionType">
 *     &lt;enumeration value="1.0"/>
 *     &lt;enumeration value="1.1"/>
 *     &lt;enumeration value="1.2"/>
 *     &lt;enumeration value="1.3"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "SupportedVersionsType")
@XmlEnum
public enum SupportedVersionsType {

    @XmlEnumValue("1.0")
    VERSION_1_0("1.0"),
    @XmlEnumValue("1.1")
    VERSION_1_1("1.1"),
    @XmlEnumValue("1.2")
    VERSION_1_2("1.2"),
    @XmlEnumValue("1.3")
    VERSION_1_3("1.3");
    private final String value;

    SupportedVersionsType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SupportedVersionsType fromValue(String v) {
        for (SupportedVersionsType c: SupportedVersionsType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
