select EX.ID AS "Ex.Id", INP.ID AS "In.ID", EX.PHASE,
 	INP.INPUT_IDENTIFIER, INP.REQUEST_ID, INP.RESPONSE_ID, ST.NAME AS
 	"Status", INP.RETURN_TEXT from EXECUTION ex, COMMUNICATION_PROTOCOL 
	inp, STATUS st where EX.ID = INP.EXECUTION_ID and INP.STATUS_ID = st.ID order by EX.ID, INP.ID;