<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="extra"
		targetNamespace="http://www.extra-standard.de/namespace/webservice"
		xmlns:extraws="http://www.extra-standard.de/namespace/webservice"
		xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
		xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
		xmlns:extrarequest="http://www.extra-standard.de/namespace/request/1"
		xmlns:extraresponse="http://www.extra-standard.de/namespace/response/1"
		xmlns:extraerror="http://www.extra-standard.de/namespace/service/1"
		xmlns:xsd="http://www.w3.org/2001/XMLSchema">

 	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://www.extra-standard.de/namespace/request/1"
					schemaLocation="eXTra-request-1.xsd" />
			<xsd:import namespace="http://www.extra-standard.de/namespace/response/1"
					schemaLocation="eXTra-response-1.xsd" />
			<xsd:import namespace="http://www.extra-standard.de/namespace/service/1"
					schemaLocation="extra-error-1.xsd" />
		</xsd:schema>
	</wsdl:types>
	
	<wsdl:message name="executeRequest">
		<wsdl:part element="extrarequest:Transport" name="request" />
	</wsdl:message>

	<wsdl:message name="executeResponse">
		<wsdl:part element="extraresponse:Transport" name="response" />
	</wsdl:message>

	<wsdl:message name="extraFault">
		<wsdl:part element="extraerror:ExtraError" name="fault" />
	</wsdl:message>
	
	<wsdl:portType name="extra">
		<wsdl:operation name="execute">
			<wsdl:input message="extraws:executeRequest" />
			<wsdl:output message="extraws:executeResponse" />
			<wsdl:fault name="fault" message="extraws:extraFault" />
		</wsdl:operation>
	</wsdl:portType>
	
	<wsdl:binding name="extraSOAP" type="extraws:extra">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http" />
		<wsdl:operation name="execute">
			<soap:operation soapAction="http://www.extra-standard.de/namespace/webservice/execute" />
			<wsdl:input>
				<soap:body use="literal" />
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" />
			</wsdl:output>
			<wsdl:fault name="fault">
				<soap:fault name="fault" use="literal" />
			</wsdl:fault>
		</wsdl:operation>
	</wsdl:binding>
	
	<wsdl:service name="extra">
		<wsdl:port binding="extraws:extraSOAP" name="extraSOAP">
			<soap:address location="http://localhost/SPoC/execute" />
		</wsdl:port>
	</wsdl:service>
	
</wsdl:definitions>