//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.24 at 11:30:02 AM CEST 
//


package de.drv.dsrv.spoc.extra.v1_3.jaxb.messages;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the de.drv.dsrv.spoc.extra.v1_3.jaxb.messages package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ListOfConfirmationOfReceipt_QNAME = new QName("http://www.extra-standard.de/namespace/message/1", "ListOfConfirmationOfReceipt");
    private final static QName _ListOfStatusResponse_QNAME = new QName("http://www.extra-standard.de/namespace/message/1", "ListOfStatusResponse");
    private final static QName _StatusRequest_QNAME = new QName("http://www.extra-standard.de/namespace/message/1", "StatusRequest");
    private final static QName _ListOfDataRequest_QNAME = new QName("http://www.extra-standard.de/namespace/message/1", "ListOfDataRequest");
    private final static QName _StatusResponse_QNAME = new QName("http://www.extra-standard.de/namespace/message/1", "StatusResponse");
    private final static QName _DataRequest_QNAME = new QName("http://www.extra-standard.de/namespace/message/1", "DataRequest");
    private final static QName _ConfirmationOfReceipt_QNAME = new QName("http://www.extra-standard.de/namespace/message/1", "ConfirmationOfReceipt");
    private final static QName _AbstractArgumentTypeLT_QNAME = new QName("http://www.extra-standard.de/namespace/message/1", "LT");
    private final static QName _AbstractArgumentTypeIN_QNAME = new QName("http://www.extra-standard.de/namespace/message/1", "IN");
    private final static QName _AbstractArgumentTypeGT_QNAME = new QName("http://www.extra-standard.de/namespace/message/1", "GT");
    private final static QName _AbstractArgumentTypeLE_QNAME = new QName("http://www.extra-standard.de/namespace/message/1", "LE");
    private final static QName _AbstractArgumentTypeGE_QNAME = new QName("http://www.extra-standard.de/namespace/message/1", "GE");
    private final static QName _AbstractArgumentTypeEQ_QNAME = new QName("http://www.extra-standard.de/namespace/message/1", "EQ");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: de.drv.dsrv.spoc.extra.v1_3.jaxb.messages
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ListOfStatusResponseType }
     * 
     */
    public ListOfStatusResponseType createListOfStatusResponseType() {
        return new ListOfStatusResponseType();
    }

    /**
     * Create an instance of {@link ListOfConfirmationOfReceiptType }
     * 
     */
    public ListOfConfirmationOfReceiptType createListOfConfirmationOfReceiptType() {
        return new ListOfConfirmationOfReceiptType();
    }

    /**
     * Create an instance of {@link ListOfDataRequestType }
     * 
     */
    public ListOfDataRequestType createListOfDataRequestType() {
        return new ListOfDataRequestType();
    }

    /**
     * Create an instance of {@link StatusResponseType }
     * 
     */
    public StatusResponseType createStatusResponseType() {
        return new StatusResponseType();
    }

    /**
     * Create an instance of {@link DataRequestType }
     * 
     */
    public DataRequestType createDataRequestType() {
        return new DataRequestType();
    }

    /**
     * Create an instance of {@link ConfirmationOfReceiptType }
     * 
     */
    public ConfirmationOfReceiptType createConfirmationOfReceiptType() {
        return new ConfirmationOfReceiptType();
    }

    /**
     * Create an instance of {@link StatusRequestType }
     * 
     */
    public StatusRequestType createStatusRequestType() {
        return new StatusRequestType();
    }

    /**
     * Create an instance of {@link StatusResponsePropertyType }
     * 
     */
    public StatusResponsePropertyType createStatusResponsePropertyType() {
        return new StatusResponsePropertyType();
    }

    /**
     * Create an instance of {@link CheckpointType }
     * 
     */
    public CheckpointType createCheckpointType() {
        return new CheckpointType();
    }

    /**
     * Create an instance of {@link OperandType }
     * 
     */
    public OperandType createOperandType() {
        return new OperandType();
    }

    /**
     * Create an instance of {@link StatusRequestQueryType }
     * 
     */
    public StatusRequestQueryType createStatusRequestQueryType() {
        return new StatusRequestQueryType();
    }

    /**
     * Create an instance of {@link PropertySetType }
     * 
     */
    public PropertySetType createPropertySetType() {
        return new PropertySetType();
    }

    /**
     * Create an instance of {@link PropertyType }
     * 
     */
    public PropertyType createPropertyType() {
        return new PropertyType();
    }

    /**
     * Create an instance of {@link OperandSetType }
     * 
     */
    public OperandSetType createOperandSetType() {
        return new OperandSetType();
    }

    /**
     * Create an instance of {@link StatusRequestArgumentType }
     * 
     */
    public StatusRequestArgumentType createStatusRequestArgumentType() {
        return new StatusRequestArgumentType();
    }

    /**
     * Create an instance of {@link ControlType }
     * 
     */
    public ControlType createControlType() {
        return new ControlType();
    }

    /**
     * Create an instance of {@link DataRequestArgumentType }
     * 
     */
    public DataRequestArgumentType createDataRequestArgumentType() {
        return new DataRequestArgumentType();
    }

    /**
     * Create an instance of {@link FlagType }
     * 
     */
    public FlagType createFlagType() {
        return new FlagType();
    }

    /**
     * Create an instance of {@link TextType }
     * 
     */
    public TextType createTextType() {
        return new TextType();
    }

    /**
     * Create an instance of {@link ValueType }
     * 
     */
    public ValueType createValueType() {
        return new ValueType();
    }

    /**
     * Create an instance of {@link ReportType }
     * 
     */
    public ReportType createReportType() {
        return new ReportType();
    }

    /**
     * Create an instance of {@link FlagCodeType }
     * 
     */
    public FlagCodeType createFlagCodeType() {
        return new FlagCodeType();
    }

    /**
     * Create an instance of {@link DataRequestQueryType }
     * 
     */
    public DataRequestQueryType createDataRequestQueryType() {
        return new DataRequestQueryType();
    }

    /**
     * Create an instance of {@link TraceType }
     * 
     */
    public TraceType createTraceType() {
        return new TraceType();
    }

    /**
     * Create an instance of {@link ListOfStatusResponseType.StatusResponse }
     * 
     */
    public ListOfStatusResponseType.StatusResponse createListOfStatusResponseTypeStatusResponse() {
        return new ListOfStatusResponseType.StatusResponse();
    }

    /**
     * Create an instance of {@link ListOfConfirmationOfReceiptType.ConfirmationOfReceipt }
     * 
     */
    public ListOfConfirmationOfReceiptType.ConfirmationOfReceipt createListOfConfirmationOfReceiptTypeConfirmationOfReceipt() {
        return new ListOfConfirmationOfReceiptType.ConfirmationOfReceipt();
    }

    /**
     * Create an instance of {@link ListOfDataRequestType.DataRequest }
     * 
     */
    public ListOfDataRequestType.DataRequest createListOfDataRequestTypeDataRequest() {
        return new ListOfDataRequestType.DataRequest();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListOfConfirmationOfReceiptType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.extra-standard.de/namespace/message/1", name = "ListOfConfirmationOfReceipt")
    public JAXBElement<ListOfConfirmationOfReceiptType> createListOfConfirmationOfReceipt(ListOfConfirmationOfReceiptType value) {
        return new JAXBElement<ListOfConfirmationOfReceiptType>(_ListOfConfirmationOfReceipt_QNAME, ListOfConfirmationOfReceiptType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListOfStatusResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.extra-standard.de/namespace/message/1", name = "ListOfStatusResponse")
    public JAXBElement<ListOfStatusResponseType> createListOfStatusResponse(ListOfStatusResponseType value) {
        return new JAXBElement<ListOfStatusResponseType>(_ListOfStatusResponse_QNAME, ListOfStatusResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StatusRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.extra-standard.de/namespace/message/1", name = "StatusRequest")
    public JAXBElement<StatusRequestType> createStatusRequest(StatusRequestType value) {
        return new JAXBElement<StatusRequestType>(_StatusRequest_QNAME, StatusRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListOfDataRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.extra-standard.de/namespace/message/1", name = "ListOfDataRequest")
    public JAXBElement<ListOfDataRequestType> createListOfDataRequest(ListOfDataRequestType value) {
        return new JAXBElement<ListOfDataRequestType>(_ListOfDataRequest_QNAME, ListOfDataRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StatusResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.extra-standard.de/namespace/message/1", name = "StatusResponse")
    public JAXBElement<StatusResponseType> createStatusResponse(StatusResponseType value) {
        return new JAXBElement<StatusResponseType>(_StatusResponse_QNAME, StatusResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DataRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.extra-standard.de/namespace/message/1", name = "DataRequest")
    public JAXBElement<DataRequestType> createDataRequest(DataRequestType value) {
        return new JAXBElement<DataRequestType>(_DataRequest_QNAME, DataRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConfirmationOfReceiptType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.extra-standard.de/namespace/message/1", name = "ConfirmationOfReceipt")
    public JAXBElement<ConfirmationOfReceiptType> createConfirmationOfReceipt(ConfirmationOfReceiptType value) {
        return new JAXBElement<ConfirmationOfReceiptType>(_ConfirmationOfReceipt_QNAME, ConfirmationOfReceiptType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OperandType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.extra-standard.de/namespace/message/1", name = "LT", scope = AbstractArgumentType.class)
    public JAXBElement<OperandType> createAbstractArgumentTypeLT(OperandType value) {
        return new JAXBElement<OperandType>(_AbstractArgumentTypeLT_QNAME, OperandType.class, AbstractArgumentType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OperandSetType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.extra-standard.de/namespace/message/1", name = "IN", scope = AbstractArgumentType.class)
    public JAXBElement<OperandSetType> createAbstractArgumentTypeIN(OperandSetType value) {
        return new JAXBElement<OperandSetType>(_AbstractArgumentTypeIN_QNAME, OperandSetType.class, AbstractArgumentType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OperandType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.extra-standard.de/namespace/message/1", name = "GT", scope = AbstractArgumentType.class)
    public JAXBElement<OperandType> createAbstractArgumentTypeGT(OperandType value) {
        return new JAXBElement<OperandType>(_AbstractArgumentTypeGT_QNAME, OperandType.class, AbstractArgumentType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OperandType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.extra-standard.de/namespace/message/1", name = "LE", scope = AbstractArgumentType.class)
    public JAXBElement<OperandType> createAbstractArgumentTypeLE(OperandType value) {
        return new JAXBElement<OperandType>(_AbstractArgumentTypeLE_QNAME, OperandType.class, AbstractArgumentType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OperandType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.extra-standard.de/namespace/message/1", name = "GE", scope = AbstractArgumentType.class)
    public JAXBElement<OperandType> createAbstractArgumentTypeGE(OperandType value) {
        return new JAXBElement<OperandType>(_AbstractArgumentTypeGE_QNAME, OperandType.class, AbstractArgumentType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OperandType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.extra-standard.de/namespace/message/1", name = "EQ", scope = AbstractArgumentType.class)
    public JAXBElement<OperandType> createAbstractArgumentTypeEQ(OperandType value) {
        return new JAXBElement<OperandType>(_AbstractArgumentTypeEQ_QNAME, OperandType.class, AbstractArgumentType.class, value);
    }

}
