//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.24 at 11:30:02 AM CEST 
//


package de.drv.dsrv.spoc.extra.v1_3.jaxb.plugins;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DataTransformsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DataTransformsType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.extra-standard.de/namespace/plugins/1}AbstractPlugInType">
 *       &lt;sequence>
 *         &lt;element name="Compression" type="{http://www.extra-standard.de/namespace/plugins/1}CompressionType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Encryption" type="{http://www.extra-standard.de/namespace/plugins/1}EncryptionType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Signature" type="{http://www.extra-standard.de/namespace/plugins/1}SignatureType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="version">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.extra-standard.de/namespace/components/1}AbstractVersionType">
 *             &lt;enumeration value="1.2"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DataTransformsType", propOrder = {
    "compression",
    "encryption",
    "signature"
})
public class DataTransformsType
    extends AbstractPlugInType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "Compression")
    protected List<CompressionType> compression;
    @XmlElement(name = "Encryption")
    protected List<EncryptionType> encryption;
    @XmlElement(name = "Signature")
    protected List<SignatureType> signature;
    @XmlAttribute(name = "version")
    protected String version;

    /**
     * Gets the value of the compression property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the compression property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCompression().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CompressionType }
     * 
     * 
     */
    public List<CompressionType> getCompression() {
        if (compression == null) {
            compression = new ArrayList<CompressionType>();
        }
        return this.compression;
    }

    /**
     * Gets the value of the encryption property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the encryption property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEncryption().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EncryptionType }
     * 
     * 
     */
    public List<EncryptionType> getEncryption() {
        if (encryption == null) {
            encryption = new ArrayList<EncryptionType>();
        }
        return this.encryption;
    }

    /**
     * Gets the value of the signature property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the signature property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSignature().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SignatureType }
     * 
     * 
     */
    public List<SignatureType> getSignature() {
        if (signature == null) {
            signature = new ArrayList<SignatureType>();
        }
        return this.signature;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

}
