//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.24 at 11:30:02 AM CEST 
//


package de.drv.dsrv.spoc.extra.v1_3.jaxb.plugins;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SignatureType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SignatureType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.extra-standard.de/namespace/plugins/1}AbstractTransformType">
 *       &lt;sequence>
 *         &lt;element name="Algorithm" type="{http://www.extra-standard.de/namespace/plugins/1}SignatureAlgorithmType"/>
 *         &lt;element name="X509Certificate" type="{http://www.extra-standard.de/namespace/plugins/1}X509CertificateType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SignatureType", propOrder = {
    "algorithm",
    "x509Certificate"
})
public class SignatureType
    extends AbstractTransformType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "Algorithm", required = true)
    protected SignatureAlgorithmType algorithm;
    @XmlElement(name = "X509Certificate")
    protected X509CertificateType x509Certificate;

    /**
     * Gets the value of the algorithm property.
     * 
     * @return
     *     possible object is
     *     {@link SignatureAlgorithmType }
     *     
     */
    public SignatureAlgorithmType getAlgorithm() {
        return algorithm;
    }

    /**
     * Sets the value of the algorithm property.
     * 
     * @param value
     *     allowed object is
     *     {@link SignatureAlgorithmType }
     *     
     */
    public void setAlgorithm(SignatureAlgorithmType value) {
        this.algorithm = value;
    }

    /**
     * Gets the value of the x509Certificate property.
     * 
     * @return
     *     possible object is
     *     {@link X509CertificateType }
     *     
     */
    public X509CertificateType getX509Certificate() {
        return x509Certificate;
    }

    /**
     * Sets the value of the x509Certificate property.
     * 
     * @param value
     *     allowed object is
     *     {@link X509CertificateType }
     *     
     */
    public void setX509Certificate(X509CertificateType value) {
        this.x509Certificate = value;
    }

}
