package de.extra_standard.namespace.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

import de.drv.dsrv.extrastandard.namespace.response.Transport;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.5-b03- Generated
 * source version: 2.1
 * 
 */
@WebService(name = "extra", targetNamespace = "http://www.extra-standard.de/namespace/webservice")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface Extra {

	/**
	 * 
	 * @param request
	 * @return returns
	 *         de.extra_standard.namespace.response._1.TransportResponseType
	 * @throws ExtraFault
	 */
	@WebMethod(action = "http://www.extra-standard.de/namespace/webservice/execute")
	@WebResult(name = "Transport", targetNamespace = "http://www.extra-standard.de/namespace/response/1", partName = "response")
	public Transport execute(
			@WebParam(name = "Transport", targetNamespace = "http://www.extra-standard.de/namespace/request/1", partName = "request") de.drv.dsrv.extrastandard.namespace.request.Transport request)
			throws ExtraFault;

}
