//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.24 at 11:30:02 AM CEST 
//


package de.drv.dsrv.spoc.extra.v1_3.jaxb.components;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{http://www.extra-standard.de/namespace/components/1}CharSequence"/>
 *         &lt;element ref="{http://www.extra-standard.de/namespace/components/1}Base64CharSequence"/>
 *         &lt;element ref="{http://www.extra-standard.de/namespace/components/1}ElementSequence"/>
 *         &lt;element ref="{http://www.extra-standard.de/namespace/components/1}AnyXML"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DataType", propOrder = {
    "charSequence",
    "base64CharSequence",
    "elementSequence",
    "anyXML"
})
public class DataType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "CharSequence")
    protected CharSequenceType charSequence;
    @XmlElement(name = "Base64CharSequence")
    protected Base64CharSequenceType base64CharSequence;
    @XmlElement(name = "ElementSequence")
    protected ElementSequenceType elementSequence;
    @XmlElement(name = "AnyXML")
    protected AnyXMLType anyXML;

    /**
     * Gets the value of the charSequence property.
     * 
     * @return
     *     possible object is
     *     {@link CharSequenceType }
     *     
     */
    public CharSequenceType getCharSequence() {
        return charSequence;
    }

    /**
     * Sets the value of the charSequence property.
     * 
     * @param value
     *     allowed object is
     *     {@link CharSequenceType }
     *     
     */
    public void setCharSequence(CharSequenceType value) {
        this.charSequence = value;
    }

    /**
     * Gets the value of the base64CharSequence property.
     * 
     * @return
     *     possible object is
     *     {@link Base64CharSequenceType }
     *     
     */
    public Base64CharSequenceType getBase64CharSequence() {
        return base64CharSequence;
    }

    /**
     * Sets the value of the base64CharSequence property.
     * 
     * @param value
     *     allowed object is
     *     {@link Base64CharSequenceType }
     *     
     */
    public void setBase64CharSequence(Base64CharSequenceType value) {
        this.base64CharSequence = value;
    }

    /**
     * Gets the value of the elementSequence property.
     * 
     * @return
     *     possible object is
     *     {@link ElementSequenceType }
     *     
     */
    public ElementSequenceType getElementSequence() {
        return elementSequence;
    }

    /**
     * Sets the value of the elementSequence property.
     * 
     * @param value
     *     allowed object is
     *     {@link ElementSequenceType }
     *     
     */
    public void setElementSequence(ElementSequenceType value) {
        this.elementSequence = value;
    }

    /**
     * Gets the value of the anyXML property.
     * 
     * @return
     *     possible object is
     *     {@link AnyXMLType }
     *     
     */
    public AnyXMLType getAnyXML() {
        return anyXML;
    }

    /**
     * Sets the value of the anyXML property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnyXMLType }
     *     
     */
    public void setAnyXML(AnyXMLType value) {
        this.anyXML = value;
    }

}
