//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.24 at 11:30:02 AM CEST 
//


package de.drv.dsrv.spoc.extra.v1_3.jaxb.logging;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import de.drv.dsrv.spoc.extra.v1_3.jaxb.components.ClassifiableIDType;


/**
 * <p>Java class for LogTraceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LogTraceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.extra-standard.de/namespace/logging/1}LogID"/>
 *         &lt;element ref="{http://www.extra-standard.de/namespace/logging/1}PreviousLogID" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LogTraceType", propOrder = {
    "logID",
    "previousLogID"
})
public class LogTraceType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "LogID", required = true)
    protected ClassifiableIDType logID;
    @XmlElement(name = "PreviousLogID")
    protected ClassifiableIDType previousLogID;

    /**
     * Gets the value of the logID property.
     * 
     * @return
     *     possible object is
     *     {@link ClassifiableIDType }
     *     
     */
    public ClassifiableIDType getLogID() {
        return logID;
    }

    /**
     * Sets the value of the logID property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClassifiableIDType }
     *     
     */
    public void setLogID(ClassifiableIDType value) {
        this.logID = value;
    }

    /**
     * Gets the value of the previousLogID property.
     * 
     * @return
     *     possible object is
     *     {@link ClassifiableIDType }
     *     
     */
    public ClassifiableIDType getPreviousLogID() {
        return previousLogID;
    }

    /**
     * Sets the value of the previousLogID property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClassifiableIDType }
     *     
     */
    public void setPreviousLogID(ClassifiableIDType value) {
        this.previousLogID = value;
    }

}
