//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.24 at 11:30:02 AM CEST 
//


package de.drv.dsrv.spoc.extra.v1_3.jaxb.logging;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;
import de.drv.dsrv.spoc.extra.v1_3.jaxb.components.ClassifiableIDType;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the de.drv.dsrv.spoc.extra.v1_3.jaxb.logging package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Exception_QNAME = new QName("http://www.extra-standard.de/namespace/logging/1", "Exception");
    private final static QName _Message_QNAME = new QName("http://www.extra-standard.de/namespace/logging/1", "Message");
    private final static QName _LogStream_QNAME = new QName("http://www.extra-standard.de/namespace/logging/1", "LogStream");
    private final static QName _PreviousLogID_QNAME = new QName("http://www.extra-standard.de/namespace/logging/1", "PreviousLogID");
    private final static QName _Event_QNAME = new QName("http://www.extra-standard.de/namespace/logging/1", "Event");
    private final static QName _LogID_QNAME = new QName("http://www.extra-standard.de/namespace/logging/1", "LogID");
    private final static QName _LogTrace_QNAME = new QName("http://www.extra-standard.de/namespace/logging/1", "LogTrace");
    private final static QName _Logging_QNAME = new QName("http://www.extra-standard.de/namespace/logging/1", "Logging");
    private final static QName _State_QNAME = new QName("http://www.extra-standard.de/namespace/logging/1", "State");
    private final static QName _StackTrace_QNAME = new QName("http://www.extra-standard.de/namespace/logging/1", "StackTrace");
    private final static QName _Parameter_QNAME = new QName("http://www.extra-standard.de/namespace/logging/1", "Parameter");
    private final static QName _Object_QNAME = new QName("http://www.extra-standard.de/namespace/logging/1", "Object");
    private final static QName _LogSequence_QNAME = new QName("http://www.extra-standard.de/namespace/logging/1", "LogSequence");
    private final static QName _Operation_QNAME = new QName("http://www.extra-standard.de/namespace/logging/1", "Operation");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: de.drv.dsrv.spoc.extra.v1_3.jaxb.logging
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link LogTraceType }
     * 
     */
    public LogTraceType createLogTraceType() {
        return new LogTraceType();
    }

    /**
     * Create an instance of {@link LogStreamType }
     * 
     */
    public LogStreamType createLogStreamType() {
        return new LogStreamType();
    }

    /**
     * Create an instance of {@link LogSequenceType }
     * 
     */
    public LogSequenceType createLogSequenceType() {
        return new LogSequenceType();
    }

    /**
     * Create an instance of {@link MessageType }
     * 
     */
    public MessageType createMessageType() {
        return new MessageType();
    }

    /**
     * Create an instance of {@link OperationType }
     * 
     */
    public OperationType createOperationType() {
        return new OperationType();
    }

    /**
     * Create an instance of {@link ParameterType }
     * 
     */
    public ParameterType createParameterType() {
        return new ParameterType();
    }

    /**
     * Create an instance of {@link ExceptionType }
     * 
     */
    public ExceptionType createExceptionType() {
        return new ExceptionType();
    }

    /**
     * Create an instance of {@link StateType }
     * 
     */
    public StateType createStateType() {
        return new StateType();
    }

    /**
     * Create an instance of {@link EventType }
     * 
     */
    public EventType createEventType() {
        return new EventType();
    }

    /**
     * Create an instance of {@link StackTraceType }
     * 
     */
    public StackTraceType createStackTraceType() {
        return new StackTraceType();
    }

    /**
     * Create an instance of {@link ObjectType }
     * 
     */
    public ObjectType createObjectType() {
        return new ObjectType();
    }

    /**
     * Create an instance of {@link LoggingType }
     * 
     */
    public LoggingType createLoggingType() {
        return new LoggingType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExceptionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.extra-standard.de/namespace/logging/1", name = "Exception")
    public JAXBElement<ExceptionType> createException(ExceptionType value) {
        return new JAXBElement<ExceptionType>(_Exception_QNAME, ExceptionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MessageType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.extra-standard.de/namespace/logging/1", name = "Message")
    public JAXBElement<MessageType> createMessage(MessageType value) {
        return new JAXBElement<MessageType>(_Message_QNAME, MessageType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LogStreamType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.extra-standard.de/namespace/logging/1", name = "LogStream")
    public JAXBElement<LogStreamType> createLogStream(LogStreamType value) {
        return new JAXBElement<LogStreamType>(_LogStream_QNAME, LogStreamType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ClassifiableIDType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.extra-standard.de/namespace/logging/1", name = "PreviousLogID")
    public JAXBElement<ClassifiableIDType> createPreviousLogID(ClassifiableIDType value) {
        return new JAXBElement<ClassifiableIDType>(_PreviousLogID_QNAME, ClassifiableIDType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EventType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.extra-standard.de/namespace/logging/1", name = "Event")
    public JAXBElement<EventType> createEvent(EventType value) {
        return new JAXBElement<EventType>(_Event_QNAME, EventType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ClassifiableIDType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.extra-standard.de/namespace/logging/1", name = "LogID")
    public JAXBElement<ClassifiableIDType> createLogID(ClassifiableIDType value) {
        return new JAXBElement<ClassifiableIDType>(_LogID_QNAME, ClassifiableIDType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LogTraceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.extra-standard.de/namespace/logging/1", name = "LogTrace")
    public JAXBElement<LogTraceType> createLogTrace(LogTraceType value) {
        return new JAXBElement<LogTraceType>(_LogTrace_QNAME, LogTraceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LoggingType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.extra-standard.de/namespace/logging/1", name = "Logging")
    public JAXBElement<LoggingType> createLogging(LoggingType value) {
        return new JAXBElement<LoggingType>(_Logging_QNAME, LoggingType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StateType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.extra-standard.de/namespace/logging/1", name = "State")
    public JAXBElement<StateType> createState(StateType value) {
        return new JAXBElement<StateType>(_State_QNAME, StateType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StackTraceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.extra-standard.de/namespace/logging/1", name = "StackTrace")
    public JAXBElement<StackTraceType> createStackTrace(StackTraceType value) {
        return new JAXBElement<StackTraceType>(_StackTrace_QNAME, StackTraceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ParameterType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.extra-standard.de/namespace/logging/1", name = "Parameter")
    public JAXBElement<ParameterType> createParameter(ParameterType value) {
        return new JAXBElement<ParameterType>(_Parameter_QNAME, ParameterType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObjectType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.extra-standard.de/namespace/logging/1", name = "Object")
    public JAXBElement<ObjectType> createObject(ObjectType value) {
        return new JAXBElement<ObjectType>(_Object_QNAME, ObjectType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LogSequenceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.extra-standard.de/namespace/logging/1", name = "LogSequence")
    public JAXBElement<LogSequenceType> createLogSequence(LogSequenceType value) {
        return new JAXBElement<LogSequenceType>(_LogSequence_QNAME, LogSequenceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OperationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.extra-standard.de/namespace/logging/1", name = "Operation")
    public JAXBElement<OperationType> createOperation(OperationType value) {
        return new JAXBElement<OperationType>(_Operation_QNAME, OperationType.class, null, value);
    }

}
