//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.24 at 11:30:02 AM CEST 
//


package de.drv.dsrv.spoc.extra.v1_3.jaxb.logging;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import de.drv.dsrv.spoc.extra.v1_3.jaxb.components.AnyXMLType;
import de.drv.dsrv.spoc.extra.v1_3.jaxb.components.TextType;


/**
 * <p>Java class for StackTraceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StackTraceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.extra-standard.de/namespace/components/1}AnyXML" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.extra-standard.de/namespace/components/1}Text" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StackTraceType", propOrder = {
    "anyXML",
    "text"
})
public class StackTraceType implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "AnyXML", namespace = "http://www.extra-standard.de/namespace/components/1")
    protected List<AnyXMLType> anyXML;
    @XmlElement(name = "Text", namespace = "http://www.extra-standard.de/namespace/components/1")
    protected List<TextType> text;

    /**
     * Gets the value of the anyXML property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the anyXML property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAnyXML().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AnyXMLType }
     * 
     * 
     */
    public List<AnyXMLType> getAnyXML() {
        if (anyXML == null) {
            anyXML = new ArrayList<AnyXMLType>();
        }
        return this.anyXML;
    }

    /**
     * Gets the value of the text property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the text property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getText().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TextType }
     * 
     * 
     */
    public List<TextType> getText() {
        if (text == null) {
            text = new ArrayList<TextType>();
        }
        return this.text;
    }

}
