//
/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-11/13/2008 12:46 PM(foreman)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.08.30 at 03:14:38 PM CEST 
//
package de.extra.client.plugins.dataplugin.auftragssatz;

import java.math.BigInteger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for compressionInfoType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="compressionInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}order"/>
 *         &lt;element ref="{}algoId"/>
 *         &lt;element ref="{}algoVersion"/>
 *         &lt;element ref="{}algoName"/>
 *         &lt;element ref="{}specUrl"/>
 *         &lt;element ref="{}specName"/>
 *         &lt;element ref="{}specVers"/>
 *         &lt;element ref="{}inputSize"/>
 *         &lt;element ref="{}outputSize"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "compressionInfoType", propOrder = { "order", "algoId",
		"algoVersion", "algoName", "specUrl", "specName", "specVers",
		"inputSize", "outputSize" })
public class CompressionInfoType {

	@XmlElement(required = true)
	protected BigInteger order;
	@XmlElement(required = true)
	protected String algoId;
	@XmlElement(required = true)
	protected String algoVersion;
	@XmlElement(required = true)
	protected String algoName;
	@XmlElement(required = true)
	protected String specUrl;
	@XmlElement(required = true)
	protected String specName;
	@XmlElement(required = true)
	protected String specVers;
	@XmlElement(required = true)
	protected BigInteger inputSize;
	@XmlElement(required = true)
	protected BigInteger outputSize;

	/**
	 * Gets the value of the order property.
	 * 
	 * @return possible object is {@link BigInteger }
	 * 
	 */
	public BigInteger getOrder() {
		return order;
	}

	/**
	 * Sets the value of the order property.
	 * 
	 * @param value
	 *            allowed object is {@link BigInteger }
	 * 
	 */
	public void setOrder(BigInteger value) {
		this.order = value;
	}

	/**
	 * Gets the value of the algoId property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getAlgoId() {
		return algoId;
	}

	/**
	 * Sets the value of the algoId property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setAlgoId(String value) {
		this.algoId = value;
	}

	/**
	 * Gets the value of the algoVersion property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getAlgoVersion() {
		return algoVersion;
	}

	/**
	 * Sets the value of the algoVersion property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setAlgoVersion(String value) {
		this.algoVersion = value;
	}

	/**
	 * Gets the value of the algoName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getAlgoName() {
		return algoName;
	}

	/**
	 * Sets the value of the algoName property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setAlgoName(String value) {
		this.algoName = value;
	}

	/**
	 * Gets the value of the specUrl property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSpecUrl() {
		return specUrl;
	}

	/**
	 * Sets the value of the specUrl property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSpecUrl(String value) {
		this.specUrl = value;
	}

	/**
	 * Gets the value of the specName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSpecName() {
		return specName;
	}

	/**
	 * Sets the value of the specName property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSpecName(String value) {
		this.specName = value;
	}

	/**
	 * Gets the value of the specVers property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSpecVers() {
		return specVers;
	}

	/**
	 * Sets the value of the specVers property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSpecVers(String value) {
		this.specVers = value;
	}

	/**
	 * Gets the value of the inputSize property.
	 * 
	 * @return possible object is {@link BigInteger }
	 * 
	 */
	public BigInteger getInputSize() {
		return inputSize;
	}

	/**
	 * Sets the value of the inputSize property.
	 * 
	 * @param value
	 *            allowed object is {@link BigInteger }
	 * 
	 */
	public void setInputSize(BigInteger value) {
		this.inputSize = value;
	}

	/**
	 * Gets the value of the outputSize property.
	 * 
	 * @return possible object is {@link BigInteger }
	 * 
	 */
	public BigInteger getOutputSize() {
		return outputSize;
	}

	/**
	 * Sets the value of the outputSize property.
	 * 
	 * @param value
	 *            allowed object is {@link BigInteger }
	 * 
	 */
	public void setOutputSize(BigInteger value) {
		this.outputSize = value;
	}
}
