/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-11/13/2008 12:46 PM(foreman)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.08.30 at 03:14:38 PM CEST 
//
package de.extra.client.plugins.dataplugin.auftragssatz;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for AuftragssatzType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="AuftragssatzType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="requestId" type="{}RequestIdType"/>
 *         &lt;element ref="{}compressionInfo" minOccurs="0"/>
 *         &lt;element ref="{}encryptionInfo" minOccurs="0"/>
 *         &lt;element ref="{}dataSourceInfo" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AuftragssatzType", propOrder = { "requestId",
		"compressionInfo", "encryptionInfo", "dataSourceInfo" })
public class AuftragssatzType {

	@XmlElement(required = true)
	protected String requestId;
	protected CompressionInfoType compressionInfo;
	protected EncryptionInfoType encryptionInfo;
	protected DataSourceInfoType dataSourceInfo;

	/**
	 * Gets the value of the requestId property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getRequestId() {
		return requestId;
	}

	/**
	 * Sets the value of the requestId property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setRequestId(String value) {
		this.requestId = value;
	}

	/**
	 * Gets the value of the compressionInfo property.
	 * 
	 * @return possible object is {@link CompressionInfoType }
	 * 
	 */
	public CompressionInfoType getCompressionInfo() {
		return compressionInfo;
	}

	/**
	 * Sets the value of the compressionInfo property.
	 * 
	 * @param value
	 *            allowed object is {@link CompressionInfoType }
	 * 
	 */
	public void setCompressionInfo(CompressionInfoType value) {
		this.compressionInfo = value;
	}

	/**
	 * Gets the value of the encryptionInfo property.
	 * 
	 * @return possible object is {@link EncryptionInfoType }
	 * 
	 */
	public EncryptionInfoType getEncryptionInfo() {
		return encryptionInfo;
	}

	/**
	 * Sets the value of the encryptionInfo property.
	 * 
	 * @param value
	 *            allowed object is {@link EncryptionInfoType }
	 * 
	 */
	public void setEncryptionInfo(EncryptionInfoType value) {
		this.encryptionInfo = value;
	}

	/**
	 * Gets the value of the dataSourceInfo property.
	 * 
	 * @return possible object is {@link DataSourceInfoType }
	 * 
	 */
	public DataSourceInfoType getDataSourceInfo() {
		return dataSourceInfo;
	}

	/**
	 * Sets the value of the dataSourceInfo property.
	 * 
	 * @param value
	 *            allowed object is {@link DataSourceInfoType }
	 * 
	 */
	public void setDataSourceInfo(DataSourceInfoType value) {
		this.dataSourceInfo = value;
	}
}
